name: Go Server Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build and test
      run: |
        go mod init
        go build -v
        go test -v ./...

    - name: Run the server and test with curl
      run: |
        ./your-executable & sleep 3
        curl -sSf http://localhost:8080/greet
        curl -sSf http://localhost:8080/info -d "name=test&email=test@example.com"
        kill $(jobs -p) || true

